import pandas as pd
df = pd.read_csv('DCCS_Train_Data.csv', nrows=20, low_memory=False)
print("STATUS unique:", df['STATUS'].unique())
print()
print("Target unique:", df['MM_Determination_Completion_Status'].unique())
print()
print("Determination_Level unique:", df['Determination_Level'].unique())
print()
print("M/M_Form_Review_Due sample:")
print(df['M/M_Form_Review_Due'].head(10))
